# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: podinfo-service
spec:
  selector:
    app: podinfo
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9898
  type: ClusterIP